name: 自动定期同步
permissions: 
  contents: write 

on: 
  schedule: 
    - cron: "0 0 * * *" # 每天 0 点运行 
  workflow_dispatch: 

jobs: 
  sync_with_upstream: 
    name: Sync with Upstream 
    runs-on: ubuntu-latest 
    if: ${{ github.event.repository.fork }} 

    steps: 
      - name: Checkout target repo 
        uses: actions/checkout@v3 
  
      - name: Sync Upstream 
        uses: tgymnich/fork-sync@v2.0.10
        with: 
          target_repo_token: ${{ secrets.GITHUB_TOKEN }} 
          owner: azerothcore
          repo: azerothcore-wotlk # 替换为上游仓库路径，例如：owner/repo 
          head: master # 上游分支名称 
          base: master # 目标分支名称 
      
      - name: Check for Failure 
        if: failure() 
        run: | 
          echo "[Error] 自动更新失败，请手动同步。" 
          exit 1
